--	Baition Units:
BAITMG = { "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG" }
BAITINF = { "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSNIPER", "BAITFLAMETHROWER", "BAITFLAMETHROWER", "BAITMEDIC", "BAITMORTAR", "BAITMORTAR", "BAITMORTAR" }
BAITV = { "BAITLTNK", "BAITLTNK", "BAITLTNK", "BAITLTNK" }

--	Marzeron Units:
MARINF1 = { "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE" }
MARINF2 = { "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK" }
MARV = { "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARLTNK", "MARLTNK", "MARLTNK", "MARLTNK", "MARLEOPARD", "MARLEOPARD" }