--	Baition Units:
BAITINF1 = { "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG" }
BAITINF2 = { "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSNIPER", "BAITFLAMETHROWER", "BAITFLAMETHROWER", "BAITMEDIC", "BAITMORTAR", "BAITMORTAR", "BAITMORTAR" }
BAITV = { "BAITLTNK", "BAITLTNK", "BAITLTNK", "BAITLTNK" }

--	Marzeron Units:
MARINF1 = { "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE" }
MARINF2 = { "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK" }
MARV = { "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARLTNK", "MARLTNK", "MARLTNK", "MARLTNK", "MARLEOPARD", "MARLEOPARD" }

-- The Seven Archangels Units:
TSAINF1 = { "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN" }
TSAINF2 = { "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSABURSTSNIPER", "TSAMECH", "TSAMECH" }
TSAV = { "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "MEDTANK", "MEDTANK", "MEDTANK", "MEDTANK", "MEDTANK", "MAMMOTH2", "OSIRIS", "OSIRIS" }

-- New Tiberium Affected Alliance Units:
NTAAINF1 = { "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA" }
NTAAINF2 = { "NTAASNPR1", "NTAASNPR1", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAAMRTR", "NTAAMRTR", "NTAAMRTR" }
NTAAV = { "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAAFHTNK", "NTAAFHTNK", "NTAAFHTNK", "NTAAFHTNK" }