bait = 1
col = 2
gsa = 3
hayl = 4
kant = 5
mar = 6
mlv = 7
ntaa = 8
rfio = 9
shyo = 10
sid = 11
trev = 12
tsa = 13
wdg = 14

FactionAssignment = function()
	if p1 == 1 then
		TEAM1INF1 = BAITINF1
		TEAM1INF2 = BAITINF2
		TEAM1V = BAITV
	elseif p1 == 2 then
		TEAM1INF1 = COLINF1
		TEAM1INF2 = COLINF2
		TEAM1V = COLV
	elseif p1 == 3 then
		TEAM1INF1 = GSAINF1
		TEAM1INF2 = GSAINF2
		TEAM1V = GSAV
	elseif p1 == 4 then
		TEAM1INF1 = HAYLINF1
		TEAM1INF2 = HAYLINF2
		TEAM1V = HAYLV
	elseif p1 == 5 then
		TEAM1INF1 = KANTINF1
		TEAM1INF2 = KANTINF2
		TEAM1V = KANTV
	elseif p1 == 6 then
		TEAM1INF1 = MARINF1
		TEAM1INF2 = MARINF2
		TEAM1V = MARV
	elseif p1 == 7 then
		TEAM1INF1 = MLVINF1
		TEAM1INF2 = MLVINF2
		TEAM1V = MLVV
	elseif p1 == 8 then
		TEAM1INF1 = NTAAINF1
		TEAM1INF2 = NTAAINF2
		TEAM1V = NTAAV
	elseif p1 == 9 then
		TEAM1INF1 = RFIOINF1
		TEAM1INF2 = RFIOINF2
		TEAM1V = RFIOV
	elseif p1 == 10 then
		TEAM1INF1 = SHYOINF1
		TEAM1INF2 = SHYOINF2
		TEAM1V = SHYOV
	elseif p1 == 11 then
		TEAM1INF1 = SIDINF1
		TEAM1INF2 = SIDINF2
		TEAM1V = SIDV
	elseif p1 == 12 then
		TEAM1INF1 = TREVINF1
		TEAM1INF2 = TREVINF2
		TEAM1V = TREVV
	elseif p1 == 13 then
		TEAM1INF1 = TSAINF1
		TEAM1INF2 = TSAINF2
		TEAM1V = TSAV
	elseif p1 == 14 then
		TEAM1INF1 = WDGINF1
		TEAM1INF2 = WDGINF2
		TEAM1V = WDGV
	end
	if p2 == 1 then
		TEAM1INF1 = BAITINF1
		TEAM1INF2 = BAITINF2
		TEAM1V = BAITV
	elseif p2 == 2 then
		TEAM1INF1 = COLINF1
		TEAM1INF2 = COLINF2
		TEAM1V = COLV
	elseif p2 == 3 then
		TEAM1INF1 = GSAINF1
		TEAM1INF2 = GSAINF2
		TEAM1V = GSAV
	elseif p2 == 4 then
		TEAM1INF1 = HAYLINF1
		TEAM1INF2 = HAYLINF2
		TEAM1V = HAYLV
	elseif p2 == 5 then
		TEAM1INF1 = KANTINF1
		TEAM1INF2 = KANTINF2
		TEAM1V = KANTV
	elseif p2 == 6 then
		TEAM1INF1 = MARINF1
		TEAM1INF2 = MARINF2
		TEAM1V = MARV
	elseif p2 == 7 then
		TEAM1INF1 = MLVINF1
		TEAM1INF2 = MLVINF2
		TEAM1V = MLVV
	elseif p2 == 8 then
		TEAM1INF1 = NTAAINF1
		TEAM1INF2 = NTAAINF2
		TEAM1V = NTAAV
	elseif p2 == 9 then
		TEAM1INF1 = RFIOINF1
		TEAM1INF2 = RFIOINF2
		TEAM1V = RFIOV
	elseif p2 == 10 then
		TEAM1INF1 = SHYOINF1
		TEAM1INF2 = SHYOINF2
		TEAM1V = SHYOV
	elseif p2 == 11 then
		TEAM1INF1 = SIDINF1
		TEAM1INF2 = SIDINF2
		TEAM1V = SIDV
	elseif p2 == 12 then
		TEAM1INF1 = TREVINF1
		TEAM1INF2 = TREVINF2
		TEAM1V = TREVV
	elseif p2 == 13 then
		TEAM1INF1 = TSAINF1
		TEAM1INF2 = TSAINF2
		TEAM1V = TSAV
	elseif p2 == 14 then
		TEAM1INF1 = WDGINF1
		TEAM1INF2 = WDGINF2
		TEAM1V = WDGV
	end
	if p3 == 1 then
		TEAM1INF1 = BAITINF1
		TEAM1INF2 = BAITINF2
		TEAM1V = BAITV
	elseif p3 == 2 then
		TEAM1INF1 = COLINF1
		TEAM1INF2 = COLINF2
		TEAM1V = COLV
	elseif p3 == 3 then
		TEAM1INF1 = GSAINF1
		TEAM1INF2 = GSAINF2
		TEAM1V = GSAV
	elseif p3 == 4 then
		TEAM1INF1 = HAYLINF1
		TEAM1INF2 = HAYLINF2
		TEAM1V = HAYLV
	elseif p3 == 5 then
		TEAM1INF1 = KANTINF1
		TEAM1INF2 = KANTINF2
		TEAM1V = KANTV
	elseif p3 == 6 then
		TEAM1INF1 = MARINF1
		TEAM1INF2 = MARINF2
		TEAM1V = MARV
	elseif p3 == 7 then
		TEAM1INF1 = MLVINF1
		TEAM1INF2 = MLVINF2
		TEAM1V = MLVV
	elseif p3 == 8 then
		TEAM1INF1 = NTAAINF1
		TEAM1INF2 = NTAAINF2
		TEAM1V = NTAAV
	elseif p3 == 9 then
		TEAM1INF1 = RFIOINF1
		TEAM1INF2 = RFIOINF2
		TEAM1V = RFIOV
	elseif p3 == 10 then
		TEAM1INF1 = SHYOINF1
		TEAM1INF2 = SHYOINF2
		TEAM1V = SHYOV
	elseif p3 == 11 then
		TEAM1INF1 = SIDINF1
		TEAM1INF2 = SIDINF2
		TEAM1V = SIDV
	elseif p3 == 12 then
		TEAM1INF1 = TREVINF1
		TEAM1INF2 = TREVINF2
		TEAM1V = TREVV
	elseif p3 == 13 then
		TEAM1INF1 = TSAINF1
		TEAM1INF2 = TSAINF2
		TEAM1V = TSAV
	elseif p3 == 14 then
		TEAM1INF1 = WDGINF1
		TEAM1INF2 = WDGINF2
		TEAM1V = WDGV
	end
	if p4 == 1 then
		TEAM1INF1 = BAITINF1
		TEAM1INF2 = BAITINF2
		TEAM1V = BAITV
	elseif p4 == 2 then
		TEAM1INF1 = COLINF1
		TEAM1INF2 = COLINF2
		TEAM1V = COLV
	elseif p4 == 3 then
		TEAM1INF1 = GSAINF1
		TEAM1INF2 = GSAINF2
		TEAM1V = GSAV
	elseif p4 == 4 then
		TEAM1INF1 = HAYLINF1
		TEAM1INF2 = HAYLINF2
		TEAM1V = HAYLV
	elseif p4 == 5 then
		TEAM1INF1 = KANTINF1
		TEAM1INF2 = KANTINF2
		TEAM1V = KANTV
	elseif p4 == 6 then
		TEAM1INF1 = MARINF1
		TEAM1INF2 = MARINF2
		TEAM1V = MARV
	elseif p4 == 7 then
		TEAM1INF1 = MLVINF1
		TEAM1INF2 = MLVINF2
		TEAM1V = MLVV
	elseif p4 == 8 then
		TEAM1INF1 = NTAAINF1
		TEAM1INF2 = NTAAINF2
		TEAM1V = NTAAV
	elseif p4 == 9 then
		TEAM1INF1 = RFIOINF1
		TEAM1INF2 = RFIOINF2
		TEAM1V = RFIOV
	elseif p4 == 10 then
		TEAM1INF1 = SHYOINF1
		TEAM1INF2 = SHYOINF2
		TEAM1V = SHYOV
	elseif p4 == 11 then
		TEAM1INF1 = SIDINF1
		TEAM1INF2 = SIDINF2
		TEAM1V = SIDV
	elseif p4 == 12 then
		TEAM1INF1 = TREVINF1
		TEAM1INF2 = TREVINF2
		TEAM1V = TREVV
	elseif p4 == 13 then
		TEAM1INF1 = TSAINF1
		TEAM1INF2 = TSAINF2
		TEAM1V = TSAV
	elseif p4 == 14 then
		TEAM1INF1 = WDGINF1
		TEAM1INF2 = WDGINF2
		TEAM1V = WDGV
	end	
end

--	Baition Units:
BAITINF1 = { "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG", "BAITMG" }
BAITINF2 = { "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSMAW", "BAITSNIPER", "BAITFLAMETHROWER", "BAITFLAMETHROWER", "BAITMEDIC", "BAITMORTAR", "BAITMORTAR", "BAITMORTAR" }
BAITV = { "BAITLTNK", "BAITLTNK", "BAITLTNK", "BAITLTNK" }

--	Marzeron Units:
MARINF1 = { "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE", "MARRIFLE" }
MARINF2 = { "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARFLAMMENWERFER", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK", "MARPANZERSHREK" }
MARV = { "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARTCH", "MARLTNK", "MARLTNK", "MARLTNK", "MARLTNK", "MARLEOPARD", "MARLEOPARD" }

-- The Seven Archangels Units:
TSAINF1 = { "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN", "TSARIFLEMAN" }
TSAINF2 = { "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSAROCKET", "TSABURSTSNIPER", "TSAMECH", "TSAMECH" }
TSAV = { "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "TSAHMV", "MEDTANK", "MEDTANK", "MEDTANK", "MEDTANK", "MEDTANK", "MAMMOTH2", "OSIRIS", "OSIRIS" }

-- New Tiberium Affected Alliance Units:
NTAAINF1 = { "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA", "NTAAMLTA" }
NTAAINF2 = { "NTAASNPR1", "NTAASNPR1", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAAMLTV", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAASMAW", "NTAAMRTR", "NTAAMRTR", "NTAAMRTR" }
NTAAV = { "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAATCH", "NTAAFHTNK", "NTAAFHTNK", "NTAAFHTNK", "NTAAFHTNK" }